In [1]:
import torch

data = torch.tensor(
    [
        [2,3,3],
        [5,6,4],
        [7,8,5]
    ]
)
data

tensor([[2, 3, 3],
        [5, 6, 4],
        [7, 8, 5]])

In [3]:
x = data[: , 0:2].float()
y = data[: ,2].float()

In [4]:
x

tensor([[2., 3.],
        [5., 6.],
        [7., 8.]])

In [5]:
y

tensor([3., 4., 5.])

### Weight initialization

In [8]:
# w=1 , b=0
def initialize_parameters():
    parameters = {}
    
    parameters['W1'] = torch.ones((2,2))*0.1
    parameters['b1'] = torch.zeros((2,1))
    
    parameters['W2'] = torch.ones((2,1))*0.1
    parameters['b2'] = torch.zeros((1,1))
    
    return parameters

In [10]:
torch.ones((2,1))*0.1

tensor([[0.1000],
        [0.1000]])

### Better way

In [11]:
def initialize_parameters(layer_dims):
    torch.manual_seed(3)
    parameters = {}
    L = len(layer_dims)
    
    for l in range(1,L):
        parameters['W'+str(l)] = torch.ones((layer_dims[l-1], layer_dims[l]))*0.1
        parameters['b'+str(l)] = torch.zeros((layer_dims[l],1))
        
        return parameters