In [2]:
import torch
print(torch.__version__)

2.5.1+cu121


In [3]:
if torch.cuda.is_available():
    print("GPU available")
    print(f"Device: {torch.cuda.get_device_name(0)}")
else:
    print("not available")

GPU available
Device: NVIDIA GeForce RTX 2050


In [4]:
a = torch.empty(2,3)
a

tensor([[1.3975e-09, 9.0804e-43, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [5]:
type(a)

torch.Tensor

In [6]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
torch.rand(2,3)

tensor([[0.8575, 0.7911, 0.1560],
        [0.9066, 0.9746, 0.4135]])

In [9]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [11]:
torch.arange(0,10,1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [13]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2145, 0.5318, 0.4321],
        [0.9781, 0.5835, 0.6459]])

## Data Type 

In [14]:
x.dtype

torch.int64

In [15]:
torch.tensor([1.0,2.0,3.0,4.0], dtype=torch.int64)

tensor([1, 2, 3, 4])

In [22]:
y = x.to(torch.float32)
y

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [23]:
y.dtype

torch.float32

## Mathmatical operations

In [19]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [20]:
x+2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [25]:
x // 3  # floor val

tensor([[0, 0, 1],
        [1, 1, 2]])

## element wise operation

In [26]:
a = torch.rand(2,3)
b = torch.rand(2,3)

In [27]:
a-b

tensor([[-0.6402, -0.0452, -0.3399],
        [ 0.1634, -0.0043, -0.2768]])

In [28]:
a%b

tensor([[0.2304, 0.3563, 0.4996],
        [0.1634, 0.0646, 0.1555]])

In [32]:
torch.clamp(a, min=1, max=3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

## Reduction operation

In [34]:
e = torch.randint(size=(2,3), low=0 , high=10, dtype=torch.float32)
e

tensor([[0., 3., 1.],
        [6., 4., 0.]])

In [35]:
torch.sum(e)

tensor(14.)

In [36]:
torch.mean(e)

tensor(2.3333)

In [39]:
# column wise sum
torch.sum(e , axis=0) 
# torch.sum(e , dim=0) 

tensor([6., 7., 1.])

In [40]:
torch.max(e)

tensor(6.)

In [41]:
torch.prod(e)

tensor(0.)

In [42]:
torch.argmax(e)

tensor(3)

## Matrix operation

In [44]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

In [45]:
torch.matmul(f,g)

tensor([[18, 23],
        [86, 63]])

In [46]:
# dot product
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

torch.dot(vector1,vector2)

tensor(11)

In [48]:
torch.transpose(f, 0,1)

tensor([[5, 9],
        [0, 8],
        [2, 5]])

In [49]:
h = torch.randint(size=(3,3), low=0 , high=10, dtype=torch.float32)

In [50]:
# determinent
torch.det(h)

tensor(5.0000)

In [51]:
torch.inverse(h)

tensor([[-8.0000,  4.0000,  1.0000],
        [ 0.2000, -0.2000,  0.2000],
        [ 1.6000, -0.6000, -0.4000]])

# special function

In [64]:
k = torch.tensor([0.001,20,30])
k

tensor([1.0000e-03, 2.0000e+01, 3.0000e+01])

In [65]:
torch.log(k)

tensor([-6.9078,  2.9957,  3.4012])

In [66]:
# exponential
torch.exp(k)

tensor([1.0010e+00, 4.8517e+08, 1.0686e+13])

In [67]:
torch.sqrt(k)

tensor([0.0316, 4.4721, 5.4772])

In [68]:
# sigmoid
torch.sigmoid(k)

tensor([0.5002, 1.0000, 1.0000])

In [71]:
# softmax
torch.softmax(k, dim=0)

tensor([9.3666e-14, 4.5398e-05, 9.9995e-01])

In [72]:
torch.relu(k)

tensor([1.0000e-03, 2.0000e+01, 3.0000e+01])

### inplace operation

In [74]:
m = torch.rand(2,3)
n = torch.rand(2,3)


In [75]:
m.add_(n)

tensor([[0.7078, 1.2518, 1.3371],
        [1.2011, 0.9550, 0.7608]])

In [76]:
m

tensor([[0.7078, 1.2518, 1.3371],
        [1.2011, 0.9550, 0.7608]])

### Coppying a tensor