In [5]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder


In [6]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head(20)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.26540,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.18600,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.24300,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.25750,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.16250,0.2364,0.07678,NaN
5,843786,M,12.45,15.70,82.57,477.1,0.12780,0.17000,0.15780,0.08089,...,23.75,103.40,741.6,0.1791,0.5249,0.5355,0.17410,0.3985,0.12440,NaN
6,844359,M,18.25,19.98,119.60,1040.0,0.09463,0.10900,0.11270,0.07400,...,27.66,153.20,1606.0,0.1442,0.2576,0.3784,0.19320,0.3063,0.08368,NaN
7,84458202,M,13.71,20.83,90.20,577.9,0.11890,0.16450,0.09366,0.05985,...,28.14,110.60,897.0,0.1654,0.3682,0.2678,0.15560,0.3196,0.11510,NaN
8,844981,M,13.00,21.82,87.50,519.8,0.12730,0.19320,0.18590,0.09353,...,30.73,106.20,739.3,0.1703,0.5401,0.5390,0.20600,0.4378,0.10720,NaN
9,84501001,M,12.46,24.04,83.97,475.9,0.11860,0.23960,0.22730,0.08543,...,40.68,97.65,711.4,0.1853,1.0580,1.1050,0.22100,0.4366,0.20750,NaN


In [7]:
df.shape

(569, 33)

In [8]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)

In [9]:
df.head(20)

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.26540,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.18600,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.24300,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.25750,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.16250,0.2364,0.07678
5,M,12.45,15.70,82.57,477.1,0.12780,0.17000,0.15780,0.08089,0.2087,...,15.47,23.75,103.40,741.6,0.1791,0.5249,0.5355,0.17410,0.3985,0.12440
6,M,18.25,19.98,119.60,1040.0,0.09463,0.10900,0.11270,0.07400,0.1794,...,22.88,27.66,153.20,1606.0,0.1442,0.2576,0.3784,0.19320,0.3063,0.08368
7,M,13.71,20.83,90.20,577.9,0.11890,0.16450,0.09366,0.05985,0.2196,...,17.06,28.14,110.60,897.0,0.1654,0.3682,0.2678,0.15560,0.3196,0.11510
8,M,13.00,21.82,87.50,519.8,0.12730,0.19320,0.18590,0.09353,0.2350,...,15.49,30.73,106.20,739.3,0.1703,0.5401,0.5390,0.20600,0.4378,0.10720
9,M,12.46,24.04,83.97,475.9,0.11860,0.23960,0.22730,0.08543,0.2030,...,15.09,40.68,97.65,711.4,0.1853,1.0580,1.1050,0.22100,0.4366,0.20750


In [10]:
x = df.iloc[: , 1:]
y = df.iloc[: , 0]

x_train, x_test, y_train, y_test  = train_test_split(
    x,y,test_size=0.2, random_state=42
)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   diagnosis                569 non-null    object 
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  5

In [12]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [13]:
encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)
y_test_encoded = encoder.transform(y_test)

In [14]:
type(y_test_encoded)

numpy.ndarray

### Numpy array to tensors conversion

In [15]:
x_train_scaled_tensor = torch.from_numpy(x_train_scaled)
x_test_scaled_tensor = torch.from_numpy(x_test_scaled)
y_train_encoded_tensor = torch.from_numpy(y_train_encoded)
x_test_encoded_tensor = torch.from_numpy(y_test_encoded)

In [16]:
type(x_train_scaled_tensor)


torch.Tensor

In [17]:
x_train_scaled_tensor.shape

torch.Size([455, 30])

In [18]:
# defining model

class MysimpleNN():
    def __init__(self,x):  # for weight and bias
        self.weights = torch.rand(x.shape[1],1 , dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1 , dtype=torch.float64 , requires_grad=True)
    
    def forward(self,x):
        z = torch.matmul(x,self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def loss_function(self,y_pred,y):
        #clump
        epsilon=1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
        loss = -(y_train_encoded_tensor*torch.log(y_pred) + (1-y_train_encoded_tensor)*torch.log(1-y_pred)).mean()
        return loss
        

In [19]:
model = MysimpleNN(x_train_scaled_tensor)
model.weights

tensor([[0.0901],
        [0.4351],
        [0.7116],
        [0.7177],
        [0.2040],
        [0.6079],
        [0.4840],
        [0.6265],
        [0.5851],
        [0.3280],
        [0.2784],
        [0.5399],
        [0.5949],
        [0.8875],
        [0.1992],
        [0.0621],
        [0.6649],
        [0.1615],
        [0.3595],
        [0.8281],
        [0.4983],
        [0.8187],
        [0.4579],
        [0.3487],
        [0.4729],
        [0.3369],
        [0.4271],
        [0.0593],
        [0.9270],
        [0.9005]], dtype=torch.float64, requires_grad=True)

In [20]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

#### Parameters

In [ ]:
epochs = 25
learning_rate = 0.1


#### Training pipeline

In [28]:
# create model 
model = MysimpleNN(x_train_scaled_tensor)

# define loop
for epoch in range(epochs):
    
    # forward pass
    y_pred = model.forward(x_train_scaled_tensor)
    
    # loss calculate
    loss = model.loss_function(y_pred, y_train_encoded_tensor)
    
    # backward pass
    loss.backward()
    
    # parameter update
    with torch.no_grad():
        model.weights -= learning_rate*model.weights.grad
        model.bias -= learning_rate*model.bias.grad
        
    # zero gradient
    model.weights.grad.zero_()
    model.bias.grad.zero_()
    
    print(f"{epoch+1}, loss = {loss.item()}")

1, loss = 3.807621082761883
2, loss = 3.6841421800721923
3, loss = 3.5589368970334236
4, loss = 3.4317162833506254
5, loss = 3.3022562141847405
6, loss = 3.1674454661345766
7, loss = 3.027517004774677
8, loss = 2.883579675364517
9, loss = 2.7328101341069218
10, loss = 2.579530057280985
11, loss = 2.4269125889877037
12, loss = 2.2735857921296416
13, loss = 2.116623690344051
14, loss = 1.9607909606058835
15, loss = 1.8076648573331695
16, loss = 1.6534535018932712
17, loss = 1.5097127820725957
18, loss = 1.3742676279829609
19, loss = 1.2529291438382346
20, loss = 1.1469603952482688
21, loss = 1.0570954332598768
22, loss = 0.9832806154988973
23, loss = 0.9245251258717412
24, loss = 0.8789765960594006
25, loss = 0.8442581131715466


In [31]:
y_pred = model.forward(x_train_scaled_tensor)  # can't take dicission looking at this
y_pred

tensor([[0.9730],
        [0.5630],
        [0.9661],
        [0.3205],
        [0.8829],
        [0.6621],
        [0.4374],
        [0.2289],
        [0.4469],
        [0.4328],
        [0.5366],
        [0.3879],
        [0.5239],
        [0.6421],
        [0.2084],
        [0.4376],
        [0.9189],
        [0.7144],
        [0.2594],
        [0.4386],
        [0.1946],
        [0.7622],
        [0.3068],
        [0.8611],
        [0.4001],
        [0.2213],
        [0.2853],
        [0.3074],
        [0.2883],
        [0.2044],
        [0.5369],
        [0.4587],
        [0.2372],
        [0.4732],
        [0.2265],
        [0.1865],
        [0.1684],
        [0.4213],
        [0.3857],
        [0.2735],
        [0.1756],
        [0.9216],
        [0.5946],
        [0.3703],
        [0.2046],
        [0.3047],
        [0.9962],
        [0.7413],
        [0.5873],
        [0.5172],
        [0.3995],
        [0.6705],
        [0.2488],
        [0.2865],
        [0.8626],
        [0

In [33]:
y_pred = (y_pred>0.9).float()
y_pred

tensor([[1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
      

In [36]:
accuracy = (y_pred == y_train_encoded_tensor)
accuracy

tensor([[False,  True, False,  ..., False,  True, False],
        [ True, False,  True,  ...,  True, False,  True],
        [False,  True, False,  ..., False,  True, False],
        ...,
        [ True, False,  True,  ...,  True, False,  True],
        [ True, False,  True,  ...,  True, False,  True],
        [ True, False,  True,  ...,  True, False,  True]])

In [37]:
accuracy = (y_pred == y_train_encoded_tensor).float()
accuracy

tensor([[0., 1., 0.,  ..., 0., 1., 0.],
        [1., 0., 1.,  ..., 1., 0., 1.],
        [0., 1., 0.,  ..., 0., 1., 0.],
        ...,
        [1., 0., 1.,  ..., 1., 0., 1.],
        [1., 0., 1.,  ..., 1., 0., 1.],
        [1., 0., 1.,  ..., 1., 0., 1.]])

In [38]:
accuracy = (y_pred == y_train_encoded_tensor).float().mean()
accuracy

tensor(0.6156)

In [39]:
with torch.no_grad():
    y_pred = model.forward(x_train_scaled_tensor)  
    y_pred = (y_pred>0.9).float()
    accuracy = (y_pred == y_train_encoded_tensor).float().mean()
    print(accuracy)
    
    
    

tensor(0.6156)
